DROP DATABASE IF EXISTS airports_dw;

CREATE DATABASE airports_dw;

USE airports_dw;

CREATE TABLE dim_origin (
    AIRPORT_ID INT,
    AIRPORT_NAME VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (AIRPORT_ID)
);

CREATE TABLE dim_destination (
    AIRPORT_ID INT,
    AIRPORT_NAME VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (AIRPORT_ID)
);

CREATE TABLE dim_departure (
    TIME_ID DATETIME,
    YEAR_ID INT,
    MONTH_ID INT,
    MONTH_NAME VARCHAR(255),
    DAY_ID INT,
    PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_arrival (
    TIME_ID DATETIME,
    YEAR_ID INT,
    MONTH_ID INT,
    MONTH_NAME VARCHAR(255),
    DAY_ID INT,
    PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_airplane (
    AIRPLANE_ID INT,
    AIRPLANE_TYPE INT,
    PRIMARY KEY (AIRPLANE_ID)
);


CREATE TABLE dim_airline (
    AIRLINE_ID INT,
    AIRLINE_TYPE INT,
    PRIMARY KEY (AIRLINE_ID)
);

CREATE TABLE fact_flight (
    FLIGHT_ID INT,
    TOTALBOOKINGS INT,
    REVENUE INT,
    AIRLINE_ID INT,
    AIRPLANE_ID INT,
    ORIGIN_ID INT,
    DESTINATION_ID INT,
    DEPARTURE DATETIME,
    ARRIVAL DATETIME,
    PRIMARY KEY (FLIGHT_ID),
    FOREIGN KEY (AIRLINE_ID) REFERENCES dim_airline (AIRLINE_ID),
    FOREIGN KEY (AIRPLANE_ID) REFERENCES dim_airplane (AIRPLANE_ID),
    FOREIGN KEY (ORIGIN_ID) REFERENCES dim_origin (AIRPORT_ID),
    FOREIGN KEY (DESTINATION_ID) REFERENCES dim_destination (AIRPORT_ID),
    FOREIGN KEY (DEPARTURE) REFERENCES dim_departure (TIME_ID),
    FOREIGN KEY (ARRIVAL) REFERENCES dim_arrival (TIME_ID)
)
